[Interface]
Address = 10.0.0.100/24
PrivateKey = yI82afp7dF3aBPxDP985HduFVqODUUBYeUVBLmcFWFw=
Table = off

[Peer]
PublicKey = dKXvxxidKBIbS6ds9dmkqkONVC1XniM5WzbH0kUGiGU=
Endpoint = 192.168.31.249:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
